image: maven:3.6-jdk-11

stages:
    - build
    - test
    - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

compile-job:
  stage: build
  script:
    - 'mvn clean compile'
  cache:
    untracked: true
  retry:
    max: 2
    when: runner_system_failure
    
unittest-job:
  stage: test
  script:
    - 'mvn test'
  dependencies:
    - compile-job
  cache:
    untracked: true
  retry:
    max: 2
    when: runner_system_failure

createjar-job:
  stage: deploy
  script:
    - 'mvn assembly:single'
  dependencies:
    - unittest-job
#  only:
#    - master
  artifacts:
    paths:
    - release/*.jar
    when: always
  retry:
    max: 2
    when: runner_system_failure
